# Generated by Django 4.2.8 on 2023-12-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='probability',
            field=models.FloatField(blank=True),
        ),
    ]
